[package]
name = "phorminx-audio"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
cpal.workspace = true
hound.workspace = true
phorminx-core = { path = "../phorminx-core" }
phorminx-session = { path = "../phorminx-session" }
ringbuf.workspace = true
rubato.workspace = true
thiserror.workspace = true
zeroize = "=1.9.0"
